/**
 * CODEOWNERS entries per workspace member directory.
 *
 * Members come from chant's read contract (./members.ts). Owners are declared
 * by member name in an owners file, so a member that moves keeps its owners.
 */

import type { Workspace } from "./members.js";

export interface OwnersConfig {
  /** Owners for the whole repository (a `*` rule). Optional. */
  default?: string[];
  /** Owners by workspace member name. */
  members?: Record<string, string[]>;
}

export class OwnersConfigError extends Error {
  constructor(message: string) {
    super(`[codeowners] ${message}`);
    this.name = "OwnersConfigError";
  }
}

const OWNER = /^@[A-Za-z0-9][A-Za-z0-9-]*(\/[A-Za-z0-9._-]+)?$|^[^\s@]+@[^\s@]+$/;

function ownerList(value: unknown, field: string): string[] {
  if (!Array.isArray(value) || value.length === 0) {
    throw new OwnersConfigError(`${field}: expected a non-empty list of owners`);
  }
  return value.map((o, i) => {
    if (typeof o !== "string" || !OWNER.test(o)) {
      throw new OwnersConfigError(`${field}[${i}]: "${String(o)}" is not an @user, @org/team or email`);
    }
    return o;
  });
}

/** Validate an owners file that was already parsed from YAML or JSON. */
export function parseOwnersConfig(raw: unknown): OwnersConfig {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new OwnersConfigError("expected an object");
  }
  const r = raw as Record<string, unknown>;
  for (const k of Object.keys(r)) {
    if (k !== "default" && k !== "members") throw new OwnersConfigError(`unknown key "${k}"`);
  }
  const out: OwnersConfig = {};
  if (r["default"] !== undefined) out.default = ownerList(r["default"], "default");
  if (r["members"] !== undefined) {
    const m = r["members"];
    if (m === null || typeof m !== "object" || Array.isArray(m)) {
      throw new OwnersConfigError("members: expected a map of member name to owners");
    }
    out.members = {};
    for (const [name, owners] of Object.entries(m as Record<string, unknown>)) {
      out.members[name] = ownerList(owners, `members.${name}`);
    }
  }
  return out;
}

export interface CodeownersResult {
  /** The file text, ending in a newline. */
  text: string;
  /** Members skipped, with why. */
  skipped: { name: string; reason: string }[];
}

function pattern(root: string, dir: string): string {
  const parts = [root, dir].filter((p) => p !== "." && p !== "");
  return parts.length === 0 ? "*" : `/${parts.join("/")}/`;
}

/**
 * Build the CODEOWNERS text. GitHub uses the last matching rule, so rules are
 * ordered by depth: a nested member's rule comes after its parent's.
 * Throws when the owners file names a member the workspace doesn't have.
 */
export function buildCodeowners(ws: Workspace, owners: OwnersConfig): CodeownersResult {
  const byName = new Map(ws.members.map((m) => [m.name, m]));
  for (const name of Object.keys(owners.members ?? {})) {
    if (!byName.has(name)) {
      throw new OwnersConfigError(
        `members.${name}: workspace "${ws.name}" has no member of that name (members: ${ws.members.map((m) => m.name).join(", ")})`,
      );
    }
  }
  const skipped: CodeownersResult["skipped"] = [];
  const rules: { pat: string; depth: number; name: string; owners: string[] }[] = [];
  for (const [name, list] of Object.entries(owners.members ?? {})) {
    const m = byName.get(name)!;
    if (m.reason === "dir-missing") {
      skipped.push({ name, reason: "its directory does not exist" });
      continue;
    }
    const pat = pattern(ws.root, m.dir);
    rules.push({ pat, depth: pat === "*" ? 0 : pat.split("/").length, name, owners: list });
  }
  rules.sort((a, b) => a.depth - b.depth || a.pat.localeCompare(b.pat));

  const lines = [
    `# Generated by github-warden from the members of workspace "${ws.name}" (chant workspace ls --json).`,
    "# Edit the owners file, not this one.",
    "",
  ];
  if (owners.default) lines.push(`* ${owners.default.join(" ")}`);
  for (const r of rules) lines.push(`${r.pat} ${r.owners.join(" ")}`);
  return { text: lines.join("\n") + "\n", skipped };
}
